[build]
  command = "yarn run build"
  publish = "/public"


[context.deploy-preview]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_ENV = "production" }
  base = "/dist"
  preview_path = "https://hitowa-test-cms.netlify.app/docs"