[build]
  # ビルドを開始する場所を変更
  base = "/dist"

  # 公開ディレクトリ
  [context.deploy-preview]
    publish = "/dist"

  # ビルドコマンド
  command = "yarn build"

  # Netlify Functions のエンドポイント対象ファイルを格納するディレクトリ
  functions = "dist/api/"


# 環境変数
[build.environment]
  VARIABLE = "value"

# リダイレクト
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 302
  force = true
  query = {id = ":id"}
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

# カスタムヘッダー
[[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''