[build]
  command = "yarn run build"
  publish = "/public"


[context.deploy-preview]
  command = "yarn docs:build"
  publish = "dist/docs/"
  environment = { NODE_ENV = "production" }
  base = "/"
  preview_path = "https://hitowa-test-cms.netlify.app/preview"